version: "3.0"
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bibliophile
      MYSQL_USER: kbroestl
      MYSQL_PASSWORD: 9Federov1
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: bibliophile
      DB_PASSWORD: password
      DB_HOST: db