version: "3.9"

services:
  mysqlbib:
    image: mysql:5.7.39
    volumes:
      - db_data_2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_PASSWORD: ${MYSQL_USER_PW}
      MYSQL_USER: bibliophile
      MYSQL_DATABASE: bibliophile
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3307:3306"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - mysqlbib
    links:
      - mysqlbib
    environment:
      DB_USER: bibliophile
      DB_NAME: bibliophile
      DB_PASSWORD: ${MYSQL_USER_PW}
      DB_HOST: mysqlbib

volumes:
  db_data_2:
